### ISSUE TITLE
接入直接crash 是什么情况

### ISSUE THREAD

**Issue by yaya2212** [KwaiAppTeam/KOOM#10]
Process: com.example.yaningzhang.androidkoom, PID: 29160
                                                   java.lang.VerifyError: Verifier rejected class com.kwai.koom.javaoom.KOOMInternal: void com.kwai.koom.javaoom.KOOMInternal.startInKOOMThread() failed to verify: void com.kwai.koom.javaoom.KOOMInternal.startInKOOMThread(): [0x2] Call site #1 bootstrap return type is not a referenceVerifier rejected class com.kwai.koom.javaoom.KOOMInternal: void com.kwai.koom.javaoom.KOOMInternal.manualTrigger() failed to verify: void com.kwai.koom.javaoom.KOOMInternal.manualTrigger(): [0x2] Call site #2 bootstrap return type is not a reference
                                                    void com.kwai.koom.javaoom.KOOMInternal.manualTriggerOnCrash() failed to verify: void com.kwai.koom.javaoom.KOOMInternal.manualTriggerOnCrash(): [0x2] Call site #3 bootstrap return type is not a reference (declaration of 'com.kwai.koom.javaoom.KOOMInternal' appears in /data/app/com.example.yaningzhang.androidkoom-VgH3DPIEOyn-OV08WGskRQ==/base.apk)
                                                       at com.kwai.koom.javaoom.KOOM.<init>(KOOM.java:43)
                                                       at com.kwai.koom.javaoom.KOOM.init(KOOM.java:62)
                                                       at com.example.yaningzhang.androidkoom.KoomApplication.onCreate(KoomApplication.java:22)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5826)
                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:176)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6651)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
08-12 11:17:42.837 29160-29160/? I/Process: Sending signal. PID: 29160 SIG: 9

!分割线
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation deps.androidx.appcompat
    implementation deps.androidx.constraintlayout
    implementation deps.material
    implementation 'com.kwai.koom:java-oom:1.0.4'
}
这个是我的配置

**Comment by AndroidInternal** [comment]
有没有尝试过clean rebuild?

依然无法解决的话，提供一下运行设备相关信息

还有提供一下gradle编译相关信息defaultConfig/compileOptions

**Comment by AndroidInternal** [comment]
太久没有回馈，无法复现，先关了
