### ISSUE TITLE
ninitializedPropertyAccessException: lateinit property commonConfig has not been initialized

### ISSUE THREAD

**Issue by jefferson0228** [KwaiAppTeam/KOOM#161]
麻烦帮忙看下，我调用startLoop之后，HeapAnalysisService里报错commonConfig没初始化，service crash了。但是在startLoop之前已经按照Demo里初始化过了，以下为初始化代码：
```
val config = CommonConfig.Builder()
        .setApplication(application) // Set application
        .setVersionNameInvoker { "1.0.0" } // Set version name, java leak feature use it
        .build()

MonitorManager.initCommonConfig(config)
      .apply { onApplicationCreate() }
```

以下为service crash的日志：
```
FATAL EXCEPTION: IntentService[HeapAnalysisService]
    Process: :heap_analysis, PID: 5118
    kotlin.UninitializedPropertyAccessException: lateinit property commonConfig has not been initialized
        at com.kwai.koom.base.MonitorManager.getCommonConfig$koom_monitor_base_release(MonitorManager.kt:33)
        at com.kwai.koom.base.MonitorBuildConfig$VERSION_NAME$2.invoke(MonitorBuildConfig.kt:28)
        at com.kwai.koom.base.MonitorBuildConfig$VERSION_NAME$2.invoke(MonitorBuildConfig.kt:23)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.kwai.koom.base.MonitorBuildConfig.getVERSION_NAME(MonitorBuildConfig.kt)
        at com.kwai.koom.javaoom.monitor.OOMFileManager.init(OOMFileManager.kt:65)
        at com.kwai.koom.javaoom.monitor.analysis.HeapAnalysisService.onHandleIntent(HeapAnalysisService.kt:190)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by AndroidInternal** [comment]
2楼正解，HeapAnalysisService进程没有初始化

**Comment by GJA-pun** [comment]
请问大佬，有提供MonitorManager初始化成功后的回调方法吗？不然这个不好用啊
