### ISSUE TITLE
java-koom混淆

### ISSUE THREAD

**Issue by leo-andr** [KwaiAppTeam/KOOM#168]
混淆处理下啊

Caused by: java.lang.IllegalAccessException: void com.kwai.koom.javaoom.monitor.OOMMonitor.<init>() is not accessible from java.lang.Class<com.kwai.koom.base.MonitorManager>
        at java.lang.Class.newInstance(Native Method)
        at com.kwai.koom.base.MonitorManager.a(MonitorManager.kt:60)

**Comment by puderty** [comment]
在项目proguard添加
-keep class com.kwai.koom.javaoom.monitor.OOMMonitor {*;}

**Comment by kingrukawa** [comment]
建议写在集成的readme里面
