### ISSUE TITLE
线程监控上报的都是系统相关信息，无应用信息，如何定位问题

### ISSUE THREAD

**Issue by xiong0320** [KwaiAppTeam/KOOM#177]
上报信息如下：
{	"createCallStack": "    #00 pc 0000000000007a8c  /system/lib64/libgraphicsenv.so (android::GraphicsEnv::hintActivityLaunch()+120)   (BuildId: efcd82044fac88fa035fee7c268f0ec2)\n    #01 pc 00000000002919f0  /data/dalvik-cache/arm64/system@framework@boot-framework.oat\n#    at android.os.GraphicsEnvironment.hintActivityLaunch(Native method)\n#    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3512)\n#    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)\n#    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)\n#    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)\n#    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)\n#    at android.os.Handler.dispatchMessage(Handler.java:107)\n#    at android.os.Looper.loop(Looper.java:214)\n#    at android.app.ActivityThread.main(ActivityThread.java:7697)\n#    at java.lang.reflect.Method.invoke(Native method)\n#    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)\n#    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)\n",	"startTime": 201401423592492,	"createTime": 201401421192336,	"endTime": 201401424899524,	"tid": 31123,	"name": "xxx:pushservice"}

**Comment by shenvsv** [comment]
暂时忽略，之后的版本会把纯系统库的问题过滤掉

**Comment by xiong0320** [comment]
邮件已收到，谢谢！copyright 熊菲苇
