### ISSUE TITLE
公司项目集成了leakcanary，再集成KOOM闪退

### ISSUE THREAD

**Issue by youzhiqingnian** [KwaiAppTeam/KOOM#19]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/leakcanary/core/R$bool;
        at leakcanary.internal.InternalLeakCanary.addDynamicShortcut(InternalLeakCanary.kt:176)
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:141)
        at leakcanary.internal.InternalLeakCanary.invoke(InternalLeakCanary.kt:38)
        at leakcanary.internal.InternalAppWatcher.install(InternalAppWatcher.kt:76)
        at leakcanary.internal.AppWatcherInstaller.onCreate(AppWatcherInstaller.kt:35)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1925)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1900)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.leakcanary.core.R$bool" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file

**Comment by AndroidInternal** [comment]
看调用栈和KOOM应该没有关系，写了个demo也没有复现。

能不能提供一个可以复现的demo，或者更多的编译相关的信息，方便复现问题。

**Comment by youzhiqingnian** [comment]
leakcanary和KOOM都集成编译能通过，打开app运行会闪退。
我在build.gradle中把集成leakcanary的依赖去掉，KOOM的集成依赖保留，打开app不会闪退

**Comment by AndroidInternal** [comment]
leakcanary版本是多少？

**Comment by youzhiqingnian** [comment]
> leakcanary版本是多少？

com.squareup.leakcanary:leakcanary-android:2.2

**Comment by AndroidInternal** [comment]
依然无法复现，这个类以及资源在apk里到底是否存在，有没有确认过？

比如用as打开，这是我这边测试的没问题的apk

![image](https://user-images.githubusercontent.com/3592681/90612886-3b0ee080-e23b-11ea-9c84-a0688a461bd4.png)
![image](https://user-images.githubusercontent.com/3592681/90612989-5a0d7280-e23b-11ea-8cea-313ba7652d1a.png)

**Comment by youzhiqingnian** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 李锐 <notifications@github.com&gt;
发送时间: 2020年8月23日 14:12
收件人: KwaiAppTeam/KOOM <KOOM@noreply.github.com&gt;
抄送: youzhiqingnian <359455763@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[KwaiAppTeam/KOOM] 公司项目集成了leakcanary，再集成KOOM闪退 (#19)





 
太久没有回馈，无法复现，问题暂时先关闭，有问题可以重新打开
