### ISSUE TITLE
恢复裁剪镜像时报错

### ISSUE THREAD

**Issue by mrqinshou** [KwaiAppTeam/KOOM#233]
使用 koom-fill-crop.jar 恢复裁剪的镜像时报错
java.nio.BufferUnderflowException
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:270)
        at com.android.tools.perflib.heap.io.MemoryMappedFileBuffer.setPosition(MemoryMappedFileBuffer.java:315)
        at com.android.tools.perflib.heap.HprofParser.skipFully(HprofParser.java:771)
        at com.android.tools.perflib.heap.HprofParser.parse(HprofParser.java:267)
        at com.android.tools.perflib.heap.Main.main(Main.java:36)
java.lang.IllegalArgumentException: Class not found: java.lang.String
        at com.android.tools.perflib.heap.Queries.instancesOf(Queries.java:156)
        at com.android.tools.perflib.heap.Main.testFindInstancesOf(Main.java:86)
        at com.android.tools.perflib.heap.Main.main(Main.java:40)
恢复出来的镜像在 AS 中打开没有内容，需要我提供导出来的裁剪后的镜像吗

**Comment by EdminhPeng** [comment]
我也遇到了，解决了吗？
