### ISSUE TITLE
dlopen failed: cannot locate symbol 错误

### ISSUE THREAD

**Issue by paopao-chen** [KwaiAppTeam/KOOM#236]
本地跑2.2.1的demo没问题，但是集成到项目中dump后开始分析时就会报这个错，还麻烦问下是什么原因导致的呢？

`
2023-03-07 16:42:18.570 15777-16272 System.err              com.dubox.drive                      W  	at com.kwai.koom.javaoom.monitor.OOMMonitor.dumpAndAnalysis(OOMMonitor.kt:309)
2023-03-07 16:42:18.570 15777-16272 System.err              com.dubox.drive                      W  	at com.kwai.koom.javaoom.monitor.OOMMonitor.access$dumpAndAnalysis(OOMMonitor.kt:40)
2023-03-07 16:42:18.570 15777-16272 System.err              com.dubox.drive                      W  	at com.kwai.koom.javaoom.monitor.OOMMonitor$trackOOM$1.invoke(OOMMonitor.kt:172)
2023-03-07 16:42:18.570 15777-16272 System.err              com.dubox.drive                      W  	at com.kwai.koom.javaoom.monitor.OOMMonitor$trackOOM$1.invoke(OOMMonitor.kt:40)
2023-03-07 16:42:18.571 15777-16272 MonitorSo               com.dubox.drive                      E  dlopen failed: cannot locate symbol "_ZNKSt6__ndk119__shared_weak_count13__get_deleterERKSt9type_info" referenced by "/data/app/~~PSi0MIBx-_3SNLaJ2wqLCg==/com.dubox.drive-XSh7G_OblN0gIXSKAXBG_w==/lib/arm64/libkwai-android-base.so"...
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNKSt6__ndk119__shared_weak_count13__get_deleterERKSt9type_info" referenced by "/data/app/~~PSi0MIBx-_3SNLaJ2wqLCg==/com.dubox.drive-XSh7G_OblN0gIXSKAXBG_w==/lib/arm64/libkwai-android-base.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.kwai.koom.base.CommonConfig$Builder$build$6.invoke(CommonConfig.kt:145)
                                                                                                    	at com.kwai.koom.base.CommonConfig$Builder$build$6.invoke(CommonConfig.kt:53)
                                                                                                    	at com.kwai.koom.base.Monitor_SoKt.loadSoQuietly(Monitor_So.kt:30)
                                                                                                    	at com.kwai.koom.fastdump.ForkJvmHeapDumper.init(ForkJvmHeapDumper.java:53)
                                                                                                    	at com.kwai.koom.fastdump.ForkJvmHeapDumper.dump(ForkJvmHeapDumper.java:65)
                                                                                                    	at com.kwai.koom.javaoom.monitor.OOMMonitor.dumpAndAnalysis(OOMMonitor.kt:309)
                                                                                                    	at com.kwai.koom.javaoom.monitor.OOMMonitor.access$dumpAndAnalysis(OOMMonitor.kt:40)
                                                                                                    	at com.kwai.koom.javaoom.monitor.OOMMonitor$trackOOM$1.invoke(OOMMonitor.kt:172)
                                                                                                    	at com.kwai.koom.javaoom.monitor.OOMMonitor$trackOOM$1.invoke(OOMMonitor.kt:40)
                                                                                                    	at com.kwai.koom.base.Monitor_ThreadKt$async$2.invoke(Monitor_Thread.kt:35)
                                                                                                    	at com.kwai.koom.base.Monitor_ThreadKt$async$2.invoke(Unknown Source:0)
                                                                                                    	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
2023-03-07 16:42:18.571 15777-16272 OOMMonitor...HeapDumper com.dubox.drive                      E  dump failed caused by so not loaded!
`

**Comment by zhubinsheng** [comment]
https://github.com/android/ndk/issues/329#issuecomment-288362664

**Comment by alhah** [comment]
你的NDK版本是多少，大概率是demo里和你线上环境依赖的libc++库版本号不同

**Comment by paopao-chen** [comment]
> 你的 NDK 版本有多少，很大概率是演示和你线上依赖环境的 libc++ 库版本号不同

项目里的是21.1.6352462
