### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tianshaokai** [KwaiAppTeam/KOOM#237]
Thread-249
Caused by: Application received signal 11 
Kernel version: 'Linux version 4.0.9 #1 SMP PREEMPT Fri Nov 5 10:47:30 CST 2021 (armv7l)'    Build fingerprint: 'asus/android_x86/x86:5.1.1/LMY49I/V9.5.3.0.LACCNFA:user/release-keys'    ABI list: 'x86,armeabi-v7a,armeabi'    ABI: 'arm'
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc8
    r0  04409fe0  r1  00000000  r2  00000708  r3  044075c8
    r4  00000000  r5  069036a0  r6  00000000  r7  8f57bef8
    r8  00000000  r9  00000000  r10 00000000  r11 00000000
    ip  00000000  sp  8f57bed8  lr  069010d9  pc  041157b0

backtrace:
    #00 pc 001157b0  /system/lib/arm/nb/libart.so (_ZN3art3Dbg9SuspendVMEv+20)
    #01 pc 000010d7  /data/app/com.xxx.xxxx.xxxx-1/lib/arm/libkoom-fast-dump.so (Java_com_kwai_koom_fastdump_ForkJvmHeapDumper_suspendAndFork+30)
    #02 pc fffffffe  <anonymous: e000000>
backtrace-end:
build id:
    /system/lib/arm/nb/libart.so (BuildId: unknown. FileSize: 4197748. LastModified: 2021-04-19T16:27:27.000+0800. MD5: 1567e26e1be021cae4963d7cc8a91034)
    /data/app/com.xxx.xxxx.xxxx-1/lib/arm/libkoom-fast-dump.so (BuildId: b9386e5cd7b5de336a1eedf4f65bda7e60cd8f12. FileSize: 7364. LastModified: 1979-12-31T01:01:02.000+0800. MD5: 719081a7ed347f9d81ce08b0be877f75)

java stack:
at com.kwai.koom.fastdump.ForkJvmHeapDumper.suspendAndFork(Native Method)
at com.kwai.koom.fastdump.ForkJvmHeapDumper.dump(ForkJvmHeapDumper.java:74)
at com.kwai.koom.javaoom.monitor.OOMMonitor.dumpAndAnalysis(OOMMonitor.kt:309)
at com.kwai.koom.javaoom.monitor.OOMMonitor.access$dumpAndAnalysis(OOMMonitor.kt:40)
at com.kwai.koom.javaoom.monitor.OOMMonitor$trackOOM$1.invoke(OOMMonitor.kt:172)
at com.kwai.koom.javaoom.monitor.OOMMonitor$trackOOM$1.invoke(OOMMonitor.kt:40)
at com.kwai.koom.base.Monitor_ThreadKt$async$2.invoke(Monitor_Thread.kt:35)
at com.kwai.koom.base.Monitor_ThreadKt$async$2.invoke(Monitor_Thread.kt)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by alhah** [comment]
这是x86的设备？
