### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libkoom-java.so" not found

### ISSUE THREAD

**Issue by Harlber** [KwaiAppTeam/KOOM#45]
环境：
 - ndk 16.1.4479499
 - 设备 模拟器 api30 
 - 系统 mac

步骤：
git clone 项目
master分支，运行demo

```java
2020-12-15 10:45:20.980 31164-31164/com.kwai.koom.demo W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libkoom-java.so" not found
2020-12-15 10:45:20.980 31164-31164/com.kwai.koom.demo W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
2020-12-15 10:45:20.981 31164-31164/com.kwai.koom.demo W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
2020-12-15 10:45:20.981 31164-31164/com.kwai.koom.demo W/System.err:     at java.lang.System.loadLibrary(System.java:1664)
2020-12-15 10:45:20.981 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.common.DefaultKSoLoader.loadLib(DefaultKSoLoader.java:25)
2020-12-15 10:45:20.981 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.dump.ForkJvmHeapDumper.<init>(ForkJvmHeapDumper.java:39)
2020-12-15 10:45:20.981 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.dump.HeapDumpTrigger.<init>(HeapDumpTrigger.java:43)
2020-12-15 10:45:20.981 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.KOOMInternal.<init>(KOOMInternal.java:60)
2020-12-15 10:45:20.982 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.KOOM.<init>(KOOM.java:43)
2020-12-15 10:45:20.982 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.KOOM.init(KOOM.java:62)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at com.kwai.koom.demo.KOOMApplication.onCreate(KOOMApplication.java:34)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:237)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.os.Looper.loop(Looper.java:223)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2020-12-15 10:45:20.986 31164-31164/com.kwai.koom.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by AndroidInternal** [comment]
x86模拟器目前还不支持

**Comment by Harlber** [comment]
好的
