### ISSUE TITLE
分析报错 用的是StripHprofHeapDumper 组件这种方式dump的内存镜像 HUWEI FLA-AL20 android9 必现

### ISSUE THREAD

**Issue by shijiannihao** [KwaiAppTeam/KOOM#46]
020-12-16 17:03:55.722 32550-32578/com.kwai.koom.demo I/LeaksFinder: build index file:/data/user/0/com.kwai.koom.demo/cache/koom/hprof/2020-12-16_17-03-51.hprof
2020-12-16 17:03:56.146 32550-32578/com.kwai.koom.demo W/System.err: java.lang.IllegalStateException: Unknown tag 0x0d at 3792519 after 0x08 at 3792506
2020-12-16 17:03:56.146 32550-32578/com.kwai.koom.demo W/System.err:     at kshark.HprofReader.readHprofRecords(HprofReader.kt:446)
2020-12-16 17:03:56.146 32550-32578/com.kwai.koom.demo W/System.err:     at kshark.internal.HprofInMemoryIndex$Companion.createReadingHprof(HprofInMemoryIndex.kt:377)
2020-12-16 17:03:56.146 32550-32578/com.kwai.koom.demo W/System.err:     at kshark.HprofHeapGraph$Companion.indexHprof(HprofHeapGraph.kt:244)
2020-12-16 17:03:56.147 32550-32578/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.analysis.SuspicionLeaksFinder.buildIndex(SuspicionLeaksFinder.java:205)
2020-12-16 17:03:56.147 32550-32578/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.analysis.SuspicionLeaksFinder.find(SuspicionLeaksFinder.java:88)
2020-12-16 17:03:56.147 32550-32578/com.kwai.koom.demo W/System.err:     at com.kwai.koom.javaoom.analysis.KHeapAnalyzer.analyze(KHeapAnalyzer.java:44)
2020-12-16 17:03:56.

**Comment by KollerWithDoris** [comment]
同样的问题  java.lang.IllegalStateException:Unknown tag 0x12 at 3331220 after 0x23 at 3331205

将StripHprofHeapDumper与ForkJvm组合起来使用会有此问题
