### ISSUE TITLE
KOOM初始化异常

### ISSUE THREAD

**Issue by crazymongo** [KwaiAppTeam/KOOM#74]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxxxs-7DlxCmcOrGT5VMbQmVIHzg==/base.apk"],nativeLibraryDirectories=[/data/app/xxxxx-7DlxCmcOrGT5VMbQmVIHzg==/lib/arm, /data/app/xxxxx-7DlxCmcOrGT5VMbQmVIHzg==/base.apk!/lib/armeabi, /system/lib, /hw_product/lib]]] couldn't find "libkoom-java.so"
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at java.lang.System.loadLibrary(System.java:1668)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at com.kwai.koom.javaoom.common.DefaultKSoLoader.loadLib(DefaultKSoLoader.java:25)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at com.kwai.koom.javaoom.dump.ForkJvmHeapDumper.<init>(ForkJvmHeapDumper.java:39)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at com.kwai.koom.javaoom.dump.HeapDumpTrigger.<init>(HeapDumpTrigger.java:43)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at com.kwai.koom.javaoom.KOOMInternal.<init>(KOOMInternal.java:60)
2021-04-14 11:52:55.230 21426-21577/com.xiwei.logistics W/System.err:     at com.kwai.koom.javaoom.KOOM.<init>(KOOM.java:43)
2021-04-14 11:52:55.231 21426-21577/com.xiwei.logistics W/System.err:     at com.kwai.koom.javaoom.KOOM.init(KOOM.java:62)

**Comment by crazymongo** [comment]
华为mate30手机上

**Comment by crazymongo** [comment]
jniLibs.srcDir的问题，收到把相关的so库拷贝到项目下就ok了
